//USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//USER LOGOUT
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

//USER PROFILE
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//USER UPDATE
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// FETCH USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'CREATE_USERS_FAIL';

//ARCHIVES

export const CREATE_ARCHIVE_REQUEST = 'CREATE_ARCHIVE_REQUEST';
export const CREATE_ARCHIVE_SUCCESS = 'CREATE_ARCHIVE_SUCCESS';
export const CREATE_ARCHIVE_FAIL = 'CREATE_ARCHIVE_FAIL';

// FETCH ARCHIVES
export const FETCH_ARCHIVE_REQUEST = 'FETCH_ARCHIVE_REQUEST';
export const FETCH_ARCHIVE_SUCCESS = 'FETCH_ARCHIVE_SUCCESS';
export const FETCH_ARCHIVE_FAIL = 'CREATE_ARCHIVE_FAIL';

//DELETE ARCHIVES
export const DELETE_ARCHIVE_REQUEST = 'DELETE_ARCHIVE_REQUEST';
export const DELETE_ARCHIVE_SUCCESS = 'DELETE_ARCHIVE_SUCCESS';
export const DELETE_ARCHIVE_FAIL = 'DELETE_ARCHIVE_FAIL';

//ARCHIVES DETAILS
export const ARCHIVE_DETAIL_REQUEST = 'ARCHIVE_DETAIL_REQUEST';
export const ARCHIVE_DETAIL_SUCCESS = 'ARCHIVE_DETAIL_SUCCESS';
export const ARCHIVE_DETAIL_FAIL = 'ARCHIVE_DETAIL_FAIL';

//UPDATE ARCHIVES
export const ARCHIVE_UPDATE_REQUEST = 'ARCHIVE_UPDATE_REQUEST';
export const ARCHIVE_UPDATE_SUCCESS = 'ARCHIVE_UPDATE_SUCCESS';
export const ARCHIVE_UPDATE_FAIL = 'ARCHIVE_UPDATE_FAIL';